databases:
  - name: Bookshelf_DB
    databaseName: bookshelf_db
    user: Bookshelf
    region: singapore

services:
  - type: web
    name: Bookshelf
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Bookshelf_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false